js:
  fallspeed: 20
  fallnum: 20
  blinkspeed: 10

bgs:
  - https://media.licdn.com/mpr/mpr/shrinknp_400_400/AAEAAQAAAAAAAAThAAAAJDBmMWIyNTQ4LWE5ZjQtNDAyNy1iNWJlLWM5YTI2ODI3ZTJiZQ.jpg
  - https://www.linode.com/media/images/employees/rschneberger_bw.png
  - https://lh3.googleusercontent.com/-NnjeAHRpWoA/AAAAAAAAAAI/AAAAAAAAAC8/uAL5pPIO1Po/photo.jpg
  - https://i.imgur.com/igZA2YQ.jpg
  - https://s-media-cache-ak0.pinimg.com/originals/62/d2/ca/62d2ca289e9fc410d2c7b1befdef1c05.png
  - https://s-media-cache-ak0.pinimg.com/736x/7c/1f/88/7c1f8803e508508de7e9ce7eeca81524.jpg
  - https://i.imgur.com/PKhHT0H.jpg
  - http://i.imgur.com/sgKsbEJ.png
  - http://i.imgur.com/Xk25nnE.png
fgs:
  - http://i.imgur.com/xDoA7oL.png
  - http://static.memecdn.com/images/avatars/s_950479_520e211358df4.png
  - http://a.deviantart.net/avatars/g/r/grossplz.png
  - http://i.imgur.com/oZPX0bb.png
  - http://3.bp.blogspot.com/-m6z-dXqGBSE/UASYZl6WgpI/AAAAAAAADCE/mmhYBDyhrj4/s320/meme%2Bpop%2B%2B-%2BCompleto%2BCreate.png
  - https://d304k3mn1nwj0a.cloudfront.net/meme/fap-guy.png
  - https://tgram.ru/wiki/stickers/imagepng/Memesmemeseverywhere/Memesmemeseverywhere_13.png
  - https://i.imgur.com/kch84GA.png
  - http://www.downloads.ws/android/public/android_images/9b8236e1a97a5deca426a4340a43318a.png
  - http://i.imgur.com/RDLgoFh.png
  - http://i.imgur.com/RDLgoFh.png
  - http://i.imgur.com/RDLgoFh.png
  - http://i.imgur.com/RDLgoFh.png
  - http://i.imgur.com/m4Eahkj.png
  - http://i.imgur.com/m4Eahkj.png
  - http://i.imgur.com/m4Eahkj.png
  - http://i.imgur.com/ymZZDLu.png
  - http://i.imgur.com/ymZZDLu.png
songs:
  - https://d1490khl9dq1ow.cloudfront.net/music/mp3preview/fun-guitar-and-ukulele-full_fk4ltN4O.mp3
  - http://www.bensound.org/bensound-music/bensound-popdance.mp3
  - http://www.bensound.org/bensound-music/bensound-dance.mp3
  - http://www.bensound.org/bensound-music/bensound-adventure.mp3
  - http://fast.ewar.lt/cstrike/mp3_eng/Lady%20Gaga%20-%20Just%20dance.mp3
  - http://fast.ewar.lt/cstrike/mp3_eng/Nelly%20-%20E.I..mp3
  - http://fast.ewar.lt/cstrike/mp3_eng/Skrillex%20feat.%20Ellie%20Goulding%20-%20Summit.mp3
  - http://fast.ewar.lt/cstrike/mp3_eng/linkin_park_-_jay_z_-_numb_-_encore.mp3
  - http://132.248.192.201/Mi_musica/Beyonce/From_the_beginning_The_best/(17)%20Beyonce%20-%20Bootylicious.mp3
  - http://132.248.192.201/Mi_musica/Beyonce/From_the_beginning_The_best/(14)%20Beyonce%20-%20Single%20Ladies%20(Put%20A%20Ring%20On%20It).mp3
  - http://132.248.192.201/Mi_musica/Beyonce/From_the_beginning_The_best/(14)%20Beyonce%20-%20Single%20Ladies%20(Put%20A%20Ring%20On%20It).mp3
  - http://dl.asramusic-6.com/foreign%20full%20album/Kesha/Ke%24ha%20-%20Animal%202010/02%20-%20Tik%20Tok.mp3
  - http://dl.asramusic-6.com/foreign%20full%20album/Eminem/%282000%29%20The%20Marshall%20Mathers%20LP/02%20Kill%20You.mp3
  - https://mrtimcakes.com/files/music/alexm/Fancy.mp3
  - https://mrtimcakes.com/files/music/alexm/Gwen%20Stefani%20-%20Hollaback%20Girl.mp3
titles:
  - RYANNNNNNNNNNNN
  - WELCOME MOTHERFUCKEER
  - LOLOLOL
  - TROLOLOLOL
  - LOLLIPOPZ
  - CAN I HAZ LULZ
  - I SEE YOU
pagetexts:
  - WHY HELLO THERE
  - HELLOOOOOOO
  - RYAN I SEE Yuuu
  - NEED MOAR
  - SO MEME MUCH TROLL
  - POOPOPOPOPOP
  - SURPRISE MOTHERFUCKER
  - CAN I HAZ LULZ PLZ
  - I SEE YOU
  - WE ARE WATCHING
  - WE ARE LEGION
  - WE DO NOT FORGIVE
  - Stel bemz no melt
  - jet fuellll
